/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import org.example.TicTacToe

fun main() {
    println(TicTacToe.getTicTacToeWinner(listOf(0, 1, 0, 0, 1, 0, 0, 1, 0)));
}
